Add ECSV reader
astronomy-commons/hipscat-import pull request #288
Opened 2024-04-30 19:41 UTC by delucchi-cmu

Closes #225 

Adds basic support for an ECSV reader. Note that the astropy ecsv reader does not implement a "fast" reader, so this method is not sped up by underlying C++, and it is not possible to chunk the reads into smaller tables.

See: https://docs.astropy.org/en/stable/io/ascii/read.html#reading-large-tables-in-chunks

2024-05-01 13:48 UTC, hombit requested changes

2024-05-01 13:48 UTC, hombit commented on tests/hipscat_import/catalog/test_run_round_trip.py
I was trying to check if the result catalog has right dtypes. However both pandas and dask.dataframes cannot read the dataset complaining about Norder dtype:
```
E   pyarrow.lib.ArrowTypeError: Unable to merge: Field Norder has incompatible types: uint8 vs int32
```

Could you please modify the test to read the data and check data types?

2024-05-03 14:40 UTC, delucchi-cmu commented on tests/hipscat_import/catalog/test_run_round_trip.py
Added tests, though I wasn't able to reproduce the above error.

2024-05-03 15:57 UTC, hombit approved these changes
Thank you!

2024-05-03 16:03 UTC, merged